export const GWANGIN_LOGO_LINKS = [
  "https://liner.com/ko",
  "https://mayacrew.oopy.io/",
  "https://vacatio.career.greetinghr.com/ko/about",
  "https://www.ironpig.io/",
  "https://endohealth.ai/",
  "https://planfit.ai/ko",
  "https://theconst.recruit.roundhr.com/",
  "https://www.zd.vc/",
  "https://wrtn.career.greetinghr.com/ko/career",
  "https://teamdoeat.career.greetinghr.com/ko/home",
  "https://team.alar.my/",
  "https://soohoio.careers.team/",
  "https://eo.career.greetinghr.com/ko/hiring",
  "https://linqalpha.career.greetinghr.com/ko/intro",
  "https://blog.naver.com/asan_nanum/224042141508",
  "https://play.google.com/store/apps/details?id=com.curvedroad.newsboy&hl=ko",
  "https://neomakes.com",
  "https://vivadios.dev",
  "https://horang.it",
] as const;
